from datetime import UTC, datetime
from decimal import Decimal
from pathlib import Path
from uuid import UUID

from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.pdfgen import canvas

from app.core.config import get_settings


def format_vnd(amount: Decimal) -> str:
    return f"VND {amount:,.0f}"


class InvoicePdfService:
    def __init__(self) -> None:
        settings = get_settings()
        self.storage_dir = Path(settings.INVOICE_STORAGE_DIR)

    def build_invoice_number(self, payment_id: UUID, created_at: datetime | None = None) -> str:
        date_part = (created_at or datetime.now(UTC)).strftime("%Y%m%d")
        return f"YPG-{date_part}-{str(payment_id)[:8].upper()}"

    def generate_pdf(
        self,
        *,
        invoice_number: str,
        member_name: str,
        member_email: str,
        plan_name: str,
        amount,
        discount_amount,
        transaction_date: datetime,
        membership_start_date,
        membership_expiry_date,
    ) -> str:
        self.storage_dir.mkdir(parents=True, exist_ok=True)
        pdf_path = self.storage_dir / f"{invoice_number}.pdf"

        document = canvas.Canvas(str(pdf_path), pagesize=A4)
        width, height = A4

        document.setTitle(invoice_number)
        document.setFont("Helvetica-Bold", 22)
        document.drawString(24 * mm, height - 28 * mm, "YPGym Invoice")

        document.setFont("Helvetica", 10)
        document.drawString(24 * mm, height - 38 * mm, "YPGym Fitness Center")
        document.drawString(24 * mm, height - 44 * mm, "Membership billing receipt")

        document.setFont("Helvetica-Bold", 11)
        document.drawRightString(width - 24 * mm, height - 30 * mm, invoice_number)
        document.setFont("Helvetica", 10)
        document.drawRightString(
            width - 24 * mm,
            height - 38 * mm,
            transaction_date.strftime("%d %b %Y, %H:%M"),
        )

        y = height - 65 * mm
        document.setFont("Helvetica-Bold", 12)
        document.drawString(24 * mm, y, "Bill to")
        document.setFont("Helvetica", 10)
        document.drawString(24 * mm, y - 8 * mm, member_name)
        document.drawString(24 * mm, y - 14 * mm, member_email)

        y -= 34 * mm
        document.setFont("Helvetica-Bold", 11)
        document.drawString(24 * mm, y, "Plan")
        document.drawString(92 * mm, y, "Coverage")
        document.drawRightString(width - 24 * mm, y, "Amount")
        document.line(24 * mm, y - 3 * mm, width - 24 * mm, y - 3 * mm)

        document.setFont("Helvetica", 10)
        coverage = (
            f"{membership_start_date.strftime('%d %b %Y')} - "
            f"{membership_expiry_date.strftime('%d %b %Y')}"
        )
        document.drawString(24 * mm, y - 12 * mm, plan_name)
        document.drawString(92 * mm, y - 12 * mm, coverage)
        document.drawRightString(width - 24 * mm, y - 12 * mm, format_vnd(amount))

        y -= 34 * mm
        document.setFont("Helvetica", 10)
        document.drawRightString(width - 58 * mm, y, "Discount")
        document.drawRightString(width - 24 * mm, y, format_vnd(discount_amount))
        document.setFont("Helvetica-Bold", 12)
        document.drawRightString(width - 58 * mm, y - 10 * mm, "Paid")
        document.drawRightString(width - 24 * mm, y - 10 * mm, format_vnd(amount))

        document.setFont("Helvetica", 9)
        document.setFillColorRGB(0.35, 0.35, 0.35)
        document.drawString(
            24 * mm,
            24 * mm,
            "This invoice is generated by the YPGym development billing flow.",
        )
        document.save()

        return str(pdf_path)
