import { useQuery } from "@tanstack/react-query";
import { ArrowRight, Bell, CalendarDays, CircleUserRound, Dumbbell, Megaphone, QrCode, RefreshCw, UsersRound } from "lucide-react";
import { Link } from "react-router-dom";

import { EmptyState, ErrorState } from "@/components/common/FeedbackState";
import { MemberShell } from "@/components/layout/MemberShell";
import { StatusBadge } from "@/components/operations/OperationsUi";
import { Button } from "@/components/ui/Button";
import { useAuth } from "@/features/auth/AuthContext";
import { apiRequest } from "@/lib/apiClient";
import { toUiError } from "@/lib/apiErrors";
import { formatDate, formatDateTime } from "@/lib/format";
import type { MemberDashboardPayload } from "@/types/operations";

const actionIcons = { membership: RefreshCw, qr: QrCode, classes: CalendarDays, profile: CircleUserRound };

export function MemberDashboardPage() {
  const { token } = useAuth();
  const query = useQuery({ queryKey: ["dashboard", "me"], queryFn: ({ signal }) => apiRequest<MemberDashboardPayload>("/dashboard/me", { token, signal }), refetchInterval: 30_000 });
  if (query.isLoading) return <MemberShell><DashboardSkeleton /></MemberShell>;
  if (query.isError) return <MemberShell><div className="mx-auto max-w-6xl"><ErrorState title={toUiError(query.error).title} message={toUiError(query.error).message} action={<Button variant="outline" onClick={() => query.refetch()}>Retry dashboard</Button>} /></div></MemberShell>;
  if (!query.data) return null;
  const data = query.data;
  const next = data.upcoming_bookings[0];
  return <MemberShell><div className="mx-auto max-w-6xl">
    <section className="overflow-hidden rounded-[1.5rem] bg-primary p-7 text-primary-foreground sm:p-9"><p className="text-xs font-black uppercase tracking-[0.14em] text-secondary">Member dashboard</p><h1 className="mt-3 font-['Barlow_Condensed'] text-5xl font-bold uppercase leading-[0.88] sm:text-6xl">Good to see you, {data.member.name.split(" ")[0]}.</h1><p className="mt-4 max-w-2xl text-sm leading-6 text-primary-foreground/70">{next ? `Your next class is ${next.gym_class.title} at ${formatDateTime(next.gym_class.start_at)}.` : "Your live membership, access, facility, class, and notification state is ready."}</p><Link className="mt-6 inline-flex items-center gap-2 rounded-md bg-secondary px-4 py-2.5 text-sm font-bold text-foreground" to="/app/classes">View class schedule <ArrowRight className="size-4" aria-hidden /></Link></section>
    {data.active_broadcasts.length ? <section className="mt-5 grid gap-3">{data.active_broadcasts.map((item) => <article className="rounded-2xl border border-secondary/60 bg-secondary/15 p-5" key={item.id}><div className="flex items-start gap-4"><span className="grid size-10 shrink-0 place-items-center rounded-xl bg-primary text-secondary"><Megaphone className="size-5" aria-hidden /></span><div><p className="text-[10px] font-black uppercase tracking-wider text-primary">Active announcement</p><h2 className="mt-1 text-lg font-bold">{item.title}</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">{item.message}</p></div></div></article>)}</section> : null}
    <section className="mt-6 grid gap-4 md:grid-cols-3">
      <article className="rounded-2xl border border-border bg-card p-5"><div className="flex items-center justify-between"><p className="text-xs font-black uppercase tracking-wider text-muted-foreground">Membership</p>{data.membership ? <StatusBadge value={data.membership.status} /> : null}</div>{data.membership ? <><p className="mt-5 font-['Barlow_Condensed'] text-4xl font-bold uppercase">{data.membership.days_remaining} days</p><p className="mt-2 text-sm font-bold">{data.membership.plan_name}</p><p className="mt-1 text-xs text-muted-foreground">Expires {formatDate(data.membership.expiry_date)}. {data.membership.message}</p></> : <><p className="mt-5 text-2xl font-bold">No membership</p><p className="mt-2 text-sm text-muted-foreground">Choose a plan to unlock QR access and class booking.</p></>}<Link className="mt-5 inline-flex items-center gap-2 text-sm font-bold text-primary" to="/memberships">{data.membership ? "Renew membership" : "Buy membership"}<ArrowRight className="size-4" aria-hidden /></Link></article>
      <article className={`rounded-2xl border p-5 ${data.qr_access.eligible ? "border-primary bg-primary text-primary-foreground" : "border-border bg-muted/50"}`}><QrCode className={`size-7 ${data.qr_access.eligible ? "text-secondary" : "text-muted-foreground"}`} aria-hidden /><p className="mt-5 text-xs font-black uppercase tracking-wider">QR access</p><p className="mt-2 text-2xl font-bold">{data.qr_access.eligible ? "Ready to scan" : "Access restricted"}</p><p className={`mt-2 text-xs leading-5 ${data.qr_access.eligible ? "text-primary-foreground/70" : "text-muted-foreground"}`}>{data.qr_access.reason ?? "Open your rotating pass at the gym entrance."}</p>{data.qr_access.eligible ? <Link className="mt-5 inline-flex items-center gap-2 rounded-md bg-secondary px-4 py-2 text-sm font-bold text-foreground" to={data.qr_access.target}>Show QR <ArrowRight className="size-4" /></Link> : null}</article>
      <article className="rounded-2xl border border-border bg-card p-5"><UsersRound className="size-7 text-primary" aria-hidden /><p className="mt-5 text-xs font-black uppercase tracking-wider text-muted-foreground">Gym crowdedness</p><p className="mt-2 font-['Barlow_Condensed'] text-4xl font-bold uppercase">{data.crowdedness.percentage}%</p><p className="mt-1 text-sm font-bold">{data.crowdedness.status}</p><p className="mt-2 text-xs text-muted-foreground">{data.crowdedness.active_count} of {data.crowdedness.capacity} places currently occupied.</p><div className="mt-5 h-2 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-secondary" style={{ width: `${Math.min(data.crowdedness.percentage, 100)}%` }} /></div></article>
    </section>
    <section className="mt-6 rounded-2xl border border-border bg-card p-5"><h2 className="text-lg font-bold">Quick actions</h2><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{data.quick_actions.map((action) => { const Icon = actionIcons[action.key as keyof typeof actionIcons] ?? Dumbbell; return action.enabled ? <Link className="rounded-xl border border-border p-4 transition hover:-translate-y-0.5 hover:bg-muted" to={action.target} key={action.key}><Icon className="size-5 text-primary" aria-hidden /><strong className="mt-3 block text-sm">{action.label}</strong></Link> : <div className="rounded-xl border border-border bg-muted/40 p-4 text-muted-foreground" aria-disabled="true" title={action.reason ?? undefined} key={action.key}><Icon className="size-5" aria-hidden /><strong className="mt-3 block text-sm">{action.label}</strong><span className="mt-1 block text-xs">Unavailable</span></div>; })}</div></section>
    <section className="mt-6 grid gap-5 lg:grid-cols-2"><article className="rounded-2xl border border-border bg-card p-5"><div className="flex items-center justify-between"><div><h2 className="text-lg font-bold">Upcoming bookings</h2><p className="mt-1 text-xs text-muted-foreground">Your next three confirmed classes.</p></div><Link className="text-sm font-bold text-primary" to="/app/bookings">View all</Link></div>{data.upcoming_bookings.length ? <ul className="mt-4 grid gap-3">{data.upcoming_bookings.map((booking) => <li className="rounded-xl bg-muted/50 p-4" key={booking.id}><div className="flex items-start justify-between gap-3"><div><strong>{booking.gym_class.title}</strong><p className="mt-1 text-xs text-muted-foreground">{formatDateTime(booking.gym_class.start_at)} / {booking.gym_class.location}</p></div><StatusBadge value={booking.status} /></div></li>)}</ul> : <EmptyState className="mt-4" title="No upcoming bookings" message="Book a class to see it here." />}{data.active_waitlists.length ? <div className="mt-5 border-t border-border pt-4"><p className="text-xs font-black uppercase tracking-wider text-muted-foreground">Active waitlists</p>{data.active_waitlists.map((entry) => <p className="mt-2 text-sm" key={entry.id}>{entry.gym_class.title} / position {entry.position}</p>)}</div> : null}</article>
      <article className="rounded-2xl border border-border bg-card p-5"><div className="flex items-center justify-between"><div><h2 className="text-lg font-bold">Notifications</h2><p className="mt-1 text-xs text-muted-foreground">{data.unread_notification_count} unread</p></div><Bell className="size-5 text-primary" aria-hidden /></div>{data.recent_notifications.length ? <ul className="mt-4 grid gap-3">{data.recent_notifications.map((item) => <li className="rounded-xl border border-border p-4" key={item.id}><strong className="text-sm">{item.title}</strong><p className="mt-1 text-xs leading-5 text-muted-foreground">{item.message}</p></li>)}</ul> : <EmptyState className="mt-4" title="No notifications" message="Booking and membership updates will appear here." />}<Link className="mt-4 inline-flex items-center gap-2 text-sm font-bold text-primary" to="/app/notifications">Open inbox <ArrowRight className="size-4" aria-hidden /></Link></article>
    </section>
  </div></MemberShell>;
}

function DashboardSkeleton() { return <div className="mx-auto max-w-6xl animate-pulse" role="status" aria-label="Loading member dashboard"><div className="h-64 rounded-[1.5rem] bg-muted" /><div className="mt-6 grid gap-4 md:grid-cols-3">{[1, 2, 3].map((item) => <div className="h-64 rounded-2xl bg-muted" key={item} />)}</div><div className="mt-6 h-40 rounded-2xl bg-muted" /><span className="sr-only">Loading member dashboard</span></div>; }
